AWSTemplateFormatVersion: '2010-09-09'
Resources:
  iam1:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: iam1
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
