AWSTemplateFormatVersion: '2010-09-09'
Resources:
  rdspublic1:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: admin
      MasterUserPassword: change-me-for-test-only
      PubliclyAccessible: true
      StorageEncrypted: true
